//! End-to-end integration test exercising the real FFI boundary.
//!
//! Unlike the unit tests (which call `Hsm` directly), this loads the built
//! `cdylib` with `libloading`, obtains the dispatch table via
//! `C_GetFunctionList`, and drives every call through that table — the exact
//! path a real PKCS#11 consumer takes. It covers the translation layer the
//! unit tests cannot reach: pointer parsing, the two-call output-buffer
//! protocol, mechanism-parameter decoding, and `CK_RV` mapping.
//!
//! Because the module keeps its state in process-global statics, the whole
//! scenario runs as a single test in a deliberate order.

use std::ffi::c_void;
use std::ptr;

/// The crate's own PKCS#11 bindings, generated by the build script into
/// `OUT_DIR`. `include!`ing them here (rather than redeclaring constants and
/// structs by hand) keeps the test in lockstep with the real ABI — the
/// dispatch table, every `CK_*` constant, and the mechanism/attribute structs
/// come straight from `pkcs11.h`. The `extern "C"` function declarations it
/// also emits are unused (we resolve symbols via `libloading`) and impose no
/// link-time dependency.
#[allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
mod raw {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

type CkGetFunctionList = unsafe extern "C" fn(*mut raw::CK_FUNCTION_LIST_PTR) -> raw::CK_RV;

const SO_PIN: &[u8] = b"so-pin-123456";
const USER_PIN: &[u8] = b"user-pin-123456";

fn module_path() -> std::path::PathBuf {
    // The test binary lives in target/<profile>/deps/; the cdylib is one
    // directory up in target/<profile>/.
    let mut dir = std::env::current_exe().expect("current_exe");
    dir.pop();
    if dir.ends_with("deps") {
        dir.pop();
    }

    // `cargo test` compiles the crate as a test harness but does not rebuild
    // the standalone cdylib this test dlopens, so a plain `cargo test` would
    // silently run against a stale (or missing) `.so`. Build it here for the
    // matching profile; the outer cargo has released its build lock by the
    // time tests execute, so this nested invocation is safe.
    let mut cargo = std::process::Command::new(env!("CARGO"));
    cargo.args(["build", "--lib"]).current_dir(env!("CARGO_MANIFEST_DIR"));

    let release = dir.ends_with("release");
    if release {
        cargo.arg("--release");
    }
    let status = cargo.status().expect("run cargo build");
    assert!(status.success(), "cargo build of the cdylib failed");

    let lib = dir.join("librustssm.so");
    assert!(lib.exists(), "built module not found at {}", lib.display());
    lib
}

fn attr(type_: raw::CK_ATTRIBUTE_TYPE, value: *const impl Sized, len: usize) -> raw::CK_ATTRIBUTE {
    raw::CK_ATTRIBUTE {
        type_,
        pValue: value as *mut c_void,
        ulValueLen: len as raw::CK_ULONG,
    }
}

fn no_param(mechanism: raw::CK_MECHANISM_TYPE) -> raw::CK_MECHANISM {
    raw::CK_MECHANISM {
        mechanism,
        pParameter: ptr::null_mut(),
        ulParameterLen: 0,
    }
}

#[test]
fn pkcs11_end_to_end() {
    // Isolate the object store in a throwaway database.
    let db = std::env::temp_dir().join(format!("rustssm-it-{}.db", std::process::id()));
    let _ = std::fs::remove_file(&db);
    std::env::set_var("RUSTSSM_DATABASE_URL", &db);

    let library = unsafe { libloading::Library::new(module_path()) }.expect("load module");
    let get_list: libloading::Symbol<CkGetFunctionList> =
        unsafe { library.get(b"C_GetFunctionList") }.expect("C_GetFunctionList symbol");

    let mut list_ptr: raw::CK_FUNCTION_LIST_PTR = ptr::null_mut();
    assert_eq!(unsafe { get_list(&mut list_ptr) }, raw::CKR_OK);
    assert!(!list_ptr.is_null());
    let fl = unsafe { &*list_ptr };

    let c_initialize = fl.C_Initialize.expect("C_Initialize present");
    let c_finalize = fl.C_Finalize.expect("C_Finalize present");
    let c_get_slot_list = fl.C_GetSlotList.unwrap();
    let c_init_token = fl.C_InitToken.unwrap();
    let c_init_pin = fl.C_InitPIN.unwrap();
    let c_open_session = fl.C_OpenSession.unwrap();
    let c_close_session = fl.C_CloseSession.unwrap();
    let c_login = fl.C_Login.unwrap();
    let c_logout = fl.C_Logout.unwrap();
    let c_destroy_object = fl.C_DestroyObject.unwrap();
    let c_create_object = fl.C_CreateObject.unwrap();
    let c_generate_key = fl.C_GenerateKey.unwrap();
    let c_generate_key_pair = fl.C_GenerateKeyPair.unwrap();
    let c_sign_init = fl.C_SignInit.unwrap();
    let c_sign = fl.C_Sign.unwrap();
    let c_verify_init = fl.C_VerifyInit.unwrap();
    let c_verify = fl.C_Verify.unwrap();
    let c_encrypt_init = fl.C_EncryptInit.unwrap();
    let c_encrypt = fl.C_Encrypt.unwrap();
    let c_decrypt_init = fl.C_DecryptInit.unwrap();
    let c_decrypt = fl.C_Decrypt.unwrap();

    // --- calls before C_Initialize are rejected -------------------------
    let mut session: raw::CK_SESSION_HANDLE = 0;
    assert_eq!(
        unsafe {
            c_open_session(
                0,
                raw::CKF_SERIAL_SESSION | raw::CKF_RW_SESSION,
                ptr::null_mut(),
                None,
                &mut session,
            )
        },
        raw::CKR_CRYPTOKI_NOT_INITIALIZED,
        "operations must fail before C_Initialize"
    );

    // --- initialize (and reject a second initialize) --------------------
    assert_eq!(unsafe { c_initialize(ptr::null_mut()) }, raw::CKR_OK);
    assert_eq!(
        unsafe { c_initialize(ptr::null_mut()) },
        raw::CKR_CRYPTOKI_ALREADY_INITIALIZED
    );

    // --- slot list via the two-call length protocol ---------------------
    let mut slot_count: raw::CK_ULONG = 0;
    assert_eq!(
        unsafe { c_get_slot_list(raw::CK_TRUE as raw::CK_BBOOL, ptr::null_mut(), &mut slot_count) },
        raw::CKR_OK
    );
    assert!(slot_count > 0, "expected at least one slot");
    let mut slots = vec![0 as raw::CK_SLOT_ID; slot_count as usize];
    assert_eq!(
        unsafe { c_get_slot_list(raw::CK_TRUE as raw::CK_BBOOL, slots.as_mut_ptr(), &mut slot_count) },
        raw::CKR_OK
    );
    let slot = slots[0];

    // --- initialize token, set the user PIN as SO -----------------------
    let mut label = *b"rustssm integration test token  "; // exactly 32 bytes
    assert_eq!(
        unsafe {
            c_init_token(
                slot,
                SO_PIN.as_ptr() as *mut u8,
                SO_PIN.len() as raw::CK_ULONG,
                label.as_mut_ptr(),
            )
        },
        raw::CKR_OK
    );

    assert_eq!(
        unsafe {
            c_open_session(
                slot,
                raw::CKF_SERIAL_SESSION | raw::CKF_RW_SESSION,
                ptr::null_mut(),
                None,
                &mut session,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(
        unsafe {
            c_login(
                session,
                raw::CKU_SO as raw::CK_USER_TYPE,
                SO_PIN.as_ptr() as *mut u8,
                SO_PIN.len() as raw::CK_ULONG,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(
        unsafe { c_init_pin(session, USER_PIN.as_ptr() as *mut u8, USER_PIN.len() as raw::CK_ULONG) },
        raw::CKR_OK
    );
    assert_eq!(unsafe { c_logout(session) }, raw::CKR_OK);

    // --- wrong user PIN is rejected, correct one succeeds ---------------
    let wrong = b"wrong-pin";
    assert_eq!(
        unsafe {
            c_login(
                session,
                raw::CKU_USER as raw::CK_USER_TYPE,
                wrong.as_ptr() as *mut u8,
                wrong.len() as raw::CK_ULONG,
            )
        },
        raw::CKR_PIN_INCORRECT
    );
    assert_eq!(
        unsafe {
            c_login(
                session,
                raw::CKU_USER as raw::CK_USER_TYPE,
                USER_PIN.as_ptr() as *mut u8,
                USER_PIN.len() as raw::CK_ULONG,
            )
        },
        raw::CKR_OK
    );

    // --- ECDSA key pair, sign/verify, buffer protocol, tamper -----------
    let priv_label = b"ec-private";
    let token_false: raw::CK_BBOOL = 0;
    let private_true: raw::CK_BBOOL = raw::CK_TRUE as raw::CK_BBOOL;
    let priv_template = [
        attr(raw::CKA_TOKEN, &token_false, 1),
        attr(raw::CKA_PRIVATE, &private_true, 1),
        attr(raw::CKA_LABEL, priv_label.as_ptr(), priv_label.len()),
    ];
    let pub_label = b"ec-public";
    let pub_template = [attr(raw::CKA_LABEL, pub_label.as_ptr(), pub_label.len())];

    let keygen = no_param(raw::CKM_EC_KEY_PAIR_GEN);
    let mut public_key: raw::CK_OBJECT_HANDLE = 0;
    let mut private_key: raw::CK_OBJECT_HANDLE = 0;
    assert_eq!(
        unsafe {
            c_generate_key_pair(
                session,
                &keygen as *const _ as *mut _,
                pub_template.as_ptr() as *mut _,
                pub_template.len() as raw::CK_ULONG,
                priv_template.as_ptr() as *mut _,
                priv_template.len() as raw::CK_ULONG,
                &mut public_key,
                &mut private_key,
            )
        },
        raw::CKR_OK
    );

    // CKM_ECDSA operates on a pre-computed digest.
    let digest = [0x5Au8; 32];
    let ecdsa = no_param(raw::CKM_ECDSA);

    assert_eq!(
        unsafe { c_sign_init(session, &ecdsa as *const _ as *mut _, private_key) },
        raw::CKR_OK
    );

    // Null buffer requests the signature length.
    let mut sig_len: raw::CK_ULONG = 0;
    assert_eq!(
        unsafe {
            c_sign(
                session,
                digest.as_ptr() as *mut u8,
                digest.len() as raw::CK_ULONG,
                ptr::null_mut(),
                &mut sig_len,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(sig_len, 64, "P-256 signature is 64 bytes");

    // A too-small buffer reports the requirement without consuming the op.
    let mut tiny = [0u8; 10];
    let mut tiny_len: raw::CK_ULONG = tiny.len() as raw::CK_ULONG;
    assert_eq!(
        unsafe {
            c_sign(
                session,
                digest.as_ptr() as *mut u8,
                digest.len() as raw::CK_ULONG,
                tiny.as_mut_ptr(),
                &mut tiny_len,
            )
        },
        raw::CKR_BUFFER_TOO_SMALL
    );
    assert_eq!(tiny_len, 64);

    // A correctly sized buffer produces the signature.
    let mut signature = [0u8; 64];
    let mut signature_len: raw::CK_ULONG = signature.len() as raw::CK_ULONG;
    assert_eq!(
        unsafe {
            c_sign(
                session,
                digest.as_ptr() as *mut u8,
                digest.len() as raw::CK_ULONG,
                signature.as_mut_ptr(),
                &mut signature_len,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(signature_len, 64);

    assert_eq!(
        unsafe { c_verify_init(session, &ecdsa as *const _ as *mut _, public_key) },
        raw::CKR_OK
    );
    assert_eq!(
        unsafe {
            c_verify(
                session,
                digest.as_ptr() as *mut u8,
                digest.len() as raw::CK_ULONG,
                signature.as_mut_ptr(),
                64,
            )
        },
        raw::CKR_OK
    );

    // A tampered signature fails verification.
    let mut tampered = signature;
    tampered[0] ^= 0xFF;
    assert_eq!(
        unsafe { c_verify_init(session, &ecdsa as *const _ as *mut _, public_key) },
        raw::CKR_OK
    );
    assert_eq!(
        unsafe {
            c_verify(
                session,
                digest.as_ptr() as *mut u8,
                digest.len() as raw::CK_ULONG,
                tampered.as_mut_ptr(),
                64,
            )
        },
        raw::CKR_SIGNATURE_INVALID
    );

    // --- generic secret key: HMAC sign/verify + AES-GCM encrypt ---------
    let class_secret: raw::CK_OBJECT_CLASS = raw::CKO_SECRET_KEY;
    let key_type: raw::CK_KEY_TYPE = raw::CKK_GENERIC_SECRET;
    let value_len: raw::CK_ULONG = 32;
    let sym_label = b"symmetric";
    let sym_template = [
        attr(raw::CKA_CLASS, &class_secret, size_of::<raw::CK_OBJECT_CLASS>()),
        attr(raw::CKA_KEY_TYPE, &key_type, size_of::<raw::CK_KEY_TYPE>()),
        attr(raw::CKA_VALUE_LEN, &value_len, size_of::<raw::CK_ULONG>()),
        attr(raw::CKA_LABEL, sym_label.as_ptr(), sym_label.len()),
    ];
    let sym_keygen = no_param(raw::CKM_GENERIC_SECRET_KEY_GEN);
    let mut sym_key: raw::CK_OBJECT_HANDLE = 0;
    assert_eq!(
        unsafe {
            c_generate_key(
                session,
                &sym_keygen as *const _ as *mut _,
                sym_template.as_ptr() as *mut _,
                sym_template.len() as raw::CK_ULONG,
                &mut sym_key,
            )
        },
        raw::CKR_OK
    );

    let message = b"authenticated message";
    let hmac = no_param(raw::CKM_SHA256_HMAC);
    assert_eq!(
        unsafe { c_sign_init(session, &hmac as *const _ as *mut _, sym_key) },
        raw::CKR_OK
    );
    let mut mac = [0u8; 32];
    let mut mac_len: raw::CK_ULONG = mac.len() as raw::CK_ULONG;
    assert_eq!(
        unsafe {
            c_sign(
                session,
                message.as_ptr() as *mut u8,
                message.len() as raw::CK_ULONG,
                mac.as_mut_ptr(),
                &mut mac_len,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(mac_len, 32);
    assert_eq!(
        unsafe { c_verify_init(session, &hmac as *const _ as *mut _, sym_key) },
        raw::CKR_OK
    );
    assert_eq!(
        unsafe {
            c_verify(
                session,
                message.as_ptr() as *mut u8,
                message.len() as raw::CK_ULONG,
                mac.as_mut_ptr(),
                32,
            )
        },
        raw::CKR_OK
    );

    // AES-GCM: exercises CK_GCM_PARAMS decoding and the encrypt/decrypt
    // buffer protocol. Uses a 32-byte IV (the non-96-bit GHASH path) to cover
    // the relaxed IV-length handling.
    let mut iv = [0x42u8; 32];
    let aad = b"header";
    let gcm_params = raw::CK_GCM_PARAMS {
        pIv: iv.as_mut_ptr(),
        ulIvLen: iv.len() as raw::CK_ULONG,
        ulIvBits: (iv.len() * 8) as raw::CK_ULONG,
        pAAD: aad.as_ptr() as *mut u8,
        ulAADLen: aad.len() as raw::CK_ULONG,
        ulTagBits: 128,
    };
    let gcm = raw::CK_MECHANISM {
        mechanism: raw::CKM_AES_GCM,
        pParameter: &gcm_params as *const raw::CK_GCM_PARAMS as *mut c_void,
        ulParameterLen: size_of::<raw::CK_GCM_PARAMS>() as raw::CK_ULONG,
    };
    let plaintext = b"attack at dawn";
    assert_eq!(
        unsafe { c_encrypt_init(session, &gcm as *const _ as *mut _, sym_key) },
        raw::CKR_OK
    );
    let mut ct_len: raw::CK_ULONG = 0;
    assert_eq!(
        unsafe {
            c_encrypt(
                session,
                plaintext.as_ptr() as *mut u8,
                plaintext.len() as raw::CK_ULONG,
                ptr::null_mut(),
                &mut ct_len,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(
        ct_len,
        plaintext.len() as raw::CK_ULONG + 16,
        "ciphertext = plaintext + 128-bit tag"
    );
    let mut ciphertext = vec![0u8; ct_len as usize];
    assert_eq!(
        unsafe {
            c_encrypt(
                session,
                plaintext.as_ptr() as *mut u8,
                plaintext.len() as raw::CK_ULONG,
                ciphertext.as_mut_ptr(),
                &mut ct_len,
            )
        },
        raw::CKR_OK
    );

    // Decrypt the ciphertext back under the same key and GCM parameters.
    assert_eq!(
        unsafe { c_decrypt_init(session, &gcm as *const _ as *mut _, sym_key) },
        raw::CKR_OK
    );
    let mut pt_len: raw::CK_ULONG = 0;
    assert_eq!(
        unsafe { c_decrypt(session, ciphertext.as_mut_ptr(), ct_len, ptr::null_mut(), &mut pt_len,) },
        raw::CKR_OK
    );
    assert_eq!(pt_len, plaintext.len() as raw::CK_ULONG, "plaintext = ciphertext - tag");
    let mut decrypted = vec![0u8; pt_len as usize];
    assert_eq!(
        unsafe {
            c_decrypt(
                session,
                ciphertext.as_mut_ptr(),
                ct_len,
                decrypted.as_mut_ptr(),
                &mut pt_len,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(&decrypted[..pt_len as usize], plaintext);

    // A tampered tag must fail authentication.
    assert_eq!(
        unsafe { c_decrypt_init(session, &gcm as *const _ as *mut _, sym_key) },
        raw::CKR_OK
    );
    let mut tampered = ciphertext.clone();
    tampered[0] ^= 0xFF;
    let mut junk = vec![0u8; pt_len as usize];
    let mut junk_len: raw::CK_ULONG = junk.len() as raw::CK_ULONG;
    assert_eq!(
        unsafe {
            c_decrypt(
                session,
                tampered.as_mut_ptr(),
                tampered.len() as raw::CK_ULONG,
                junk.as_mut_ptr(),
                &mut junk_len,
            )
        },
        raw::CKR_ENCRYPTED_DATA_INVALID
    );

    // --- C_CreateObject: import an AES key from a known value -----------
    let key_class: raw::CK_OBJECT_CLASS = raw::CKO_SECRET_KEY;
    let aes_key_type: raw::CK_KEY_TYPE = raw::CKK_AES;
    let raw_key = [0x2Bu8; 32];
    let ck_true: raw::CK_BBOOL = raw::CK_TRUE as raw::CK_BBOOL;
    let created_label = b"imported-aes";
    let create_template = [
        attr(raw::CKA_CLASS, &key_class, size_of::<raw::CK_OBJECT_CLASS>()),
        attr(raw::CKA_KEY_TYPE, &aes_key_type, size_of::<raw::CK_KEY_TYPE>()),
        attr(raw::CKA_VALUE, raw_key.as_ptr(), raw_key.len()),
        attr(raw::CKA_LABEL, created_label.as_ptr(), created_label.len()),
        attr(raw::CKA_TOKEN, &ck_true, size_of::<raw::CK_BBOOL>()),
        attr(raw::CKA_PRIVATE, &ck_true, size_of::<raw::CK_BBOOL>()),
    ];
    let mut created_key: raw::CK_OBJECT_HANDLE = 0;
    assert_eq!(
        unsafe {
            c_create_object(
                session,
                create_template.as_ptr() as *mut _,
                create_template.len() as raw::CK_ULONG,
                &mut created_key,
            )
        },
        raw::CKR_OK
    );

    // The imported key must be usable: encrypt with it under AES-GCM.
    assert_eq!(
        unsafe { c_encrypt_init(session, &gcm as *const _ as *mut _, created_key) },
        raw::CKR_OK
    );
    let mut created_ct_len: raw::CK_ULONG = 0;
    assert_eq!(
        unsafe {
            c_encrypt(
                session,
                plaintext.as_ptr() as *mut u8,
                plaintext.len() as raw::CK_ULONG,
                ptr::null_mut(),
                &mut created_ct_len,
            )
        },
        raw::CKR_OK
    );
    assert_eq!(created_ct_len, plaintext.len() as raw::CK_ULONG + 16);

    // --- error mapping: unsupported mechanism, invalid session ----------
    let mut ignored: raw::CK_OBJECT_HANDLE = 0;
    assert_eq!(
        unsafe {
            // CKM_ECDSA is not a key-generation mechanism.
            c_generate_key(
                session,
                &ecdsa as *const _ as *mut _,
                sym_template.as_ptr() as *mut _,
                sym_template.len() as raw::CK_ULONG,
                &mut ignored,
            )
        },
        raw::CKR_MECHANISM_INVALID
    );
    assert_eq!(unsafe { c_close_session(0xDEAD_BEEF) }, raw::CKR_SESSION_HANDLE_INVALID);

    // --- teardown -------------------------------------------------------
    assert_eq!(unsafe { c_destroy_object(session, private_key) }, raw::CKR_OK);
    assert_eq!(unsafe { c_close_session(session) }, raw::CKR_OK);
    assert_eq!(unsafe { c_finalize(ptr::null_mut()) }, raw::CKR_OK);

    drop(library);
    let _ = std::fs::remove_file(&db);
}
